 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hastatakip.gui;

import com.hastatakip.dao.*;
import com.hastatakip.entity.*;
import java.util.Date;
import java.util.HashSet;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.Set;


/**
 *
 * @author serkancam
 */
public class HastaIslemleri extends javax.swing.JFrame {

    /**
     * Creates new form AnaSayfa
     */
    public GirisSayfasi ataPencere;
    public String doktorTC;
    public HastaIslemleri() 
    {
        initComponents();
        
    }
    void NesneleriSifirla(){
        this.txtHastaAdi.setText("");
        this.txtHastaTC.setText("");
        this.txtHastaSoyadi.setText("");
        this.dtpDogumTarihi.setDate(new Date(0));
    }
    void HastaTablosuDoldur(){
        
       List<Hasta> hastalar =null;
       HastaDao islem=new HastaDao();
       hastalar=islem.TumListeyiGetir();
       DefaultTableModel model= (DefaultTableModel) tblIcerik.getModel();
        for (Hasta hasta : hastalar) {
             model.addRow(new Object[]{hasta.getHastaTC(),hasta.getHastaAdi(),hasta.getHastaSoyadi(),hasta.getHastaDogumTarihi()});
            
            
        }
       
                
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIcerik = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtHastaTC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHastaAdi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHastaSoyadi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dtpDogumTarihi = new org.jdesktop.swingx.JXDatePicker();
        btnEkle = new javax.swing.JButton();
        btnSil = new javax.swing.JButton();
        btnGuncelle = new javax.swing.JButton();
        lblHata = new javax.swing.JLabel();
        btnMuayeneEkraniAc = new javax.swing.JButton();
        lblDoktorBilgisi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tblIcerik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hasta TC", "Hasta Adı", "Hasta Soyadı", "Hasta Doğum Tarihi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblIcerik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIcerikMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblIcerik);

        jLabel1.setText("HastaTC");

        jLabel2.setText("Hasta Adı");

        jLabel3.setText("Hasta Soyadı");

        jLabel4.setText("Hasta Doğum Tarihi");

        dtpDogumTarihi.setFormats("dd.MM.yyyy");
        dtpDogumTarihi.setLinkPanel(null);

        btnEkle.setText("Ekle");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });

        btnSil.setText("Sil");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });

        btnGuncelle.setText("Güncelle");
        btnGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuncelleActionPerformed(evt);
            }
        });

        lblHata.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        lblHata.setForeground(new java.awt.Color(218, 13, 13));
        lblHata.setAutoscrolls(true);

        btnMuayeneEkraniAc.setText("Muayene Ekranını Aç");
        btnMuayeneEkraniAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuayeneEkraniAcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHata, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(btnEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(btnGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtHastaAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHastaTC, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHastaSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dtpDogumTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addComponent(btnMuayeneEkraniAc, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDoktorBilgisi, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHastaTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtHastaAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtHastaSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(dtpDogumTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEkle)
                            .addComponent(btnSil)
                            .addComponent(btnGuncelle)))
                    .addComponent(btnMuayeneEkraniAc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblHata, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblDoktorBilgisi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        // TODO add your handling code here:
       lblHata.setText("");
       DefaultTableModel model= (DefaultTableModel) tblIcerik.getModel();
       Hasta hasta =new Hasta();
       hasta.setHastaTC(txtHastaTC.getText());
       hasta.setHastaAdi(txtHastaAdi.getText());
       hasta.setHastaSoyadi(txtHastaSoyadi.getText());
       hasta.setHastaDogumTarihi(dtpDogumTarihi.getDate());
       HastaDao islem=new HastaDao();
       if(islem.Ekle(hasta)>0)
           lblHata.setText("Ekleme başarılı");
       else
           lblHata.setText("Ekleme işlemi başarısız");
       
       
       int rowCount = model.getRowCount();
//Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--)
        {
             model.removeRow(i);
        }
       HastaTablosuDoldur();
       
                  
    }//GEN-LAST:event_btnEkleActionPerformed

    private void btnGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuncelleActionPerformed
        // TODO add your handling code here:
        lblHata.setText("");
         DefaultTableModel model= (DefaultTableModel) tblIcerik.getModel();
        if(tblIcerik.getRowCount()==0){
         
            lblHata.setText("Tabloda kayıt yok");
            
        }
        else if(tblIcerik.getSelectedRow()==-1){
            lblHata.setText("lütfen bir satır seçiniz");
          
        }
        else
        {
          
         model.setValueAt(txtHastaTC.getText(), tblIcerik.getSelectedRow(), 0);
         model.setValueAt(txtHastaAdi.getText(), tblIcerik.getSelectedRow(), 1);
         model.setValueAt(txtHastaSoyadi.getText(), tblIcerik.getSelectedRow(), 2);
         model.setValueAt(dtpDogumTarihi.getDate().toString(), tblIcerik.getSelectedRow(), 3); 
        }
       Hasta hasta =new Hasta();
       hasta.setHastaTC(txtHastaTC.getText());
       hasta.setHastaAdi(txtHastaAdi.getText());
       hasta.setHastaSoyadi(txtHastaSoyadi.getText());
       hasta.setHastaDogumTarihi(dtpDogumTarihi.getDate());
       HastaDao islem=new HastaDao();
       if(islem.Guncelle(hasta)>0)
           lblHata.setText("Güncelleme başarılı");
       else
           lblHata.setText("Güncelleme işlemi başarısız");
       
       int rowCount = model.getRowCount();
//Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--)
        {
             model.removeRow(i);
        }
       HastaTablosuDoldur();
         
        
    }//GEN-LAST:event_btnGuncelleActionPerformed

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        // TODO add your handling code here:
       lblHata.setText("");
         DefaultTableModel model= (DefaultTableModel) tblIcerik.getModel();
        if(tblIcerik.getRowCount()==0){
         
            lblHata.setText("Tabloda kayıt yok");
            
        }
        else if(tblIcerik.getSelectedRow()==-1){
            lblHata.setText("lütfen bir satır seçiniz");
          
        }
        else
        {
          
         model.setValueAt(txtHastaTC.getText(), tblIcerik.getSelectedRow(), 0);
         model.setValueAt(txtHastaAdi.getText(), tblIcerik.getSelectedRow(), 1);
         model.setValueAt(txtHastaSoyadi.getText(), tblIcerik.getSelectedRow(), 2);
         model.setValueAt(dtpDogumTarihi.getDate().toString(), tblIcerik.getSelectedRow(), 3); 
        }
       Hasta hasta =new Hasta();
       hasta.setHastaTC(txtHastaTC.getText());
       hasta.setHastaAdi(txtHastaAdi.getText());
       hasta.setHastaSoyadi(txtHastaSoyadi.getText());
       hasta.setHastaDogumTarihi(dtpDogumTarihi.getDate());
       HastaDao islem=new HastaDao();
       if(islem.Sil(hasta.getHastaTC())>0)
           lblHata.setText("Silme başarılı");
       else
           lblHata.setText("Silme işlemi başarısız");
       
       int rowCount = model.getRowCount();
//Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--)
        {
             model.removeRow(i);
        }
       HastaTablosuDoldur();
    }//GEN-LAST:event_btnSilActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        HastaTablosuDoldur();
        DoktorDao doktorIslem=new DoktorDao();
        Doktor doktor= new Doktor();
        doktor.setDoktorTC("0");
        doktor=doktorIslem.TCyeGoreGetir(this.doktorTC);
        lblDoktorBilgisi.setText(doktor.toString());
                
        
    }//GEN-LAST:event_formWindowOpened

    private void tblIcerikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIcerikMouseClicked
        // TODO add your handling code here:
         lblHata.setText("");
         DefaultTableModel model= (DefaultTableModel) tblIcerik.getModel();
        if(tblIcerik.getRowCount()==0){
         
            lblHata.setText("Tabloda kayıt yok");
            
        }
        else if(tblIcerik.getSelectedRow()==-1){
            lblHata.setText("lütfen bir satır seçiniz");
          
        }
        else{
        
         txtHastaTC.setText(model.getValueAt(tblIcerik.getSelectedRow(), 0).toString());
         txtHastaAdi.setText(model.getValueAt( tblIcerik.getSelectedRow(), 1).toString());
         txtHastaSoyadi.setText(model.getValueAt( tblIcerik.getSelectedRow(), 2).toString());
         dtpDogumTarihi.setDate((Date)model.getValueAt( tblIcerik.getSelectedRow(), 3)); 
        }
    }//GEN-LAST:event_tblIcerikMouseClicked

    private void btnMuayeneEkraniAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuayeneEkraniAcActionPerformed
             // TODO add your handling code here:
            MuayeneIslemleri m=new MuayeneIslemleri();
            m.ataPencere=this;
            m.seciliDoktorTC=this.doktorTC;
            m.seciliHastaTC=txtHastaTC.getText();
            m.setVisible(true);
            this.setVisible(false);
            
                          
    }//GEN-LAST:event_btnMuayeneEkraniAcActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        ataPencere.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HastaIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HastaIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HastaIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HastaIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HastaIslemleri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnGuncelle;
    private javax.swing.JButton btnMuayeneEkraniAc;
    private javax.swing.JButton btnSil;
    private org.jdesktop.swingx.JXDatePicker dtpDogumTarihi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDoktorBilgisi;
    private javax.swing.JLabel lblHata;
    private javax.swing.JTable tblIcerik;
    private javax.swing.JTextField txtHastaAdi;
    private javax.swing.JTextField txtHastaSoyadi;
    private javax.swing.JTextField txtHastaTC;
    // End of variables declaration//GEN-END:variables
}
